# Generated by Django 4.0.6 on 2022-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='poost_id',
            new_name='post_id',
        ),
    ]
